export const CustomSelectStyles = (isMobile) => ({
  control: (provided, state) => ({
    ...provided,
    padding: "0px 14px",
    borderRadius: "12px",
    border: "1px solid rgba(25, 26, 21, 0.1)",
    backgroundColor: "#fbfbfb",
    justifyContent: "space-between",
    cursor: "pointer",
    height: isMobile ? "44px" : "52px",
    color: "#191a15",
    width: isMobile ? "100%" : "232px",
    boxShadow: "none",
    fontSize: isMobile ? "14px" : "16px",
    outline: "none",
    borderColor: state.isFocused
      ? "rgba(25, 26, 21, 0.1)"
      : "rgba(25, 26, 21, 0.1)",
    "&:hover": {
      borderColor: "rgba(25, 26, 21, 0.3)",
    },
  }),
  option: (provided, state) => ({
    ...provided,
    color: state.isDisabled || state.isSelected ? "#191a15" : "#8a8a89",
    backgroundColor: "transparent",
    paddingBottom: "0",
    cursor: "pointer",
    textAlign: state.isDisabled ? "left" : "center",
    fontSize: isMobile ? "14px" : "16px",
    marginBottom: "3px",
    lineHeight: 1.25,
    fontWeight: "500",
    fontFamily: "Inter, sans-serif",
    "&:hover": {
      backgroundColor: "transparent",
      color: "#191a15",
    },
  }),
  menu: (provided) => ({
    ...provided,
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    width: "160px",
    right: 0,
  }),
  menuList: (provided) => ({
    ...provided,
    paddingLeft: 10,
    paddingTop: 16,
    paddingBottom: 16,
    maxHeight: "180px",
    overflowY: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "#191a15",
    paddingTop: 0,
    fontSize: isMobile ? "14px" : "16px",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    margin: 0,
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
});
