export const CustomSelectStyles = {
  control: (provided, state) => ({
    ...provided,
    padding: "0px 18px",
    borderRadius: "14px",
    border: "none",
    backgroundColor: "#54be96",
    cursor: "pointer",
    height: "48px",
    width: "226px",
    boxShadow: "none",
    outline: "none",
  }),
  singleValue: (provided, state) => ({
    ...provided,
    color: "#fbfbfb",
    margin: 0,
    padding: 0,
  }),
  option: (provided, state) => ({
    ...provided,
    color: state.isSelected ? "#191a15" : "#8a8a89",
    backgroundColor: "transparent",
    paddingBottom: "0",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "16px",
    marginBottom: "1px",
    lineHeight: 1.25,
    fontWeight: "400",
    fontFamily: "Inter, sans-serif",
    "&:hover": {
      backgroundColor: "transparent",
      color: "#191a15",
    },
  }),
  menu: (provided) => ({
    ...provided,
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    width: "226px",
    right: 0,
    marginTop: "9px",
  }),
  menuList: (provided) => ({
    ...provided,
    paddingLeft: 6,
    paddingTop: 8,
    paddingBottom: 10,
    maxHeight: "226px",
    overflowY: "auto",
    scrollbarWidth: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "#fbfbfb",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    margin: 0,
    fontFamily: "Inter, sans-serif",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    color: "#fbfbfb",
    padding: "0",
    "&:hover": {
      color: "#fbfbfb",
    },
    transition: "transform 0.3s ease",
    transform: state.menuIsOpen ? "rotate(180deg)" : "rotate(0deg)",
  }),
};
